# tell travis that we a copy of docker
# build our image using dockerfile.dev
# tell travis how to run our test suite
sudo: required
services:
  - docker

before_install:
  - docker build -t ahadb/react-docker-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true ahadb/react-docker-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-aws"
  env: "Docker-react-aws-env"
  bucket_name: "elasticbeanstalk-us-east-2-717175270002"
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


